#:kivy 1.0.9

<ObstacleWrapper>:
    # Playground size is 690, 590
    #   Start at position 5, 5 to 695, 595
    # Coordination system bottom-left (5, 5) - top-right (695, 595)

    Obstacle:
        pos: 450, 360
        size: 100, 20

    Obstacle:
        pos: 255, 460
        size: 20, 60

    Obstacle:
        pos: 160, 550
        size: 60, 30

    Obstacle:
        pos: 20, 420
        size: 50, 30

    Obstacle:
        pos: 450, 450
        size: 50, 60

    Obstacle:
        pos: 510, 210
        size: 30, 20

    Obstacle:
        pos: 420, 140
        size: 90, 70

    Obstacle:
        pos: 350, 450
        size: 30, 70

    Obstacle:
        pos: 20, 140
        size: 60, 170

    Obstacle:
        pos: 150, 440
        size: 50, 60

    Obstacle:
        pos: 60, 500
        size: 40, 40

    Obstacle:
        pos: 120, 120
        size: 80, 20

    Obstacle:
        pos: 80, 30
        size: 140, 60

    Obstacle:
        pos: 270, 120
        size: 30, 20

    Obstacle:
        pos: 290, 560
        size: 70, 30

    Obstacle:
        pos: 510, 120
        size: 60, 20

    Obstacle:
        pos: 390, 210
        size: 30, 20

    Obstacle:
        pos: 610, 195
        size: 90, 70

    Obstacle:
        pos: 150, 210
        size: 30, 20

    Obstacle:
        pos: 250, 210
        size: 70, 50

    Obstacle:
        pos: 570, 355
        size: 80, 175

    Obstacle:
        pos: 390, 80
        size: 30, 60

    Obstacle:
        pos: 45, 360
        size: 40, 20

    Obstacle:
        pos: 510, 300
        size: 30, 20

    Obstacle:
        pos: 460, 550
        size: 60, 30

    Obstacle:
        pos: 125, 320
        size: 240, 60

<ObjectiveWrapper>:
    # Playground size is 690, 590
    #   Start at position 5, 5 to 695, 595
    # Coordination system bottom-left (5, 5) - top-right (695, 595)

    # Objective:
    #     pos: 500, 50
    #     size: 20, 20
