#:kivy 1.0.9

<ObstacleWrapper>:
    # Playground size is 690, 590
    #   Start at position 5, 5 to 695, 595
    # Coordination system bottom-left (5, 5) - top-right (695, 595)

    

<ObjectiveWrapper>:
    # Playground size is 690, 590
    #   Start at position 5, 5 to 695, 595
    # Coordination system bottom-left (5, 5) - top-right (695, 595)

    # Objective:
    #     pos: 500, 50
    #     size: 20, 20
