#:kivy 1.0.9

<Obstacle>:
    group: 'obs'
    pos: self.pos
    size: self.size
    canvas:
        Color:
            rgba: 0, 0, 0, 1
        Line:
            width: 1.3
            rectangle: self.pos[0], self.pos[1], self.size[0], self.size[1]

<Objective>:
    group: 'obj'
    size: 20, 20
    pos: self.pos
    canvas:
        Color:
            rgba: 0, 0, 1, 0.8
        Rectangle:
            pos: self.pos
            size: self.size

<Robot>:
    direction: 0
    size: 20, 20
    pos: self.pos
    color: 0.3, 0.35, 0.9, 0.8
    canvas.before:
        PushMatrix
        Rotate:
            angle: 360 - self._direction
            origin: self.center

        Color:
            rgba: self.color
        Line:
            width: 1.3
            circle: (self.center[0], self.center[1], 10)

        Color:
            rgba: 0, 0, 0, 0.8
        Line:
            width: 1.1
            points: self.center_x, self.center_y , self.center_x + 10, self.center_y

    canvas.after:
        PopMatrix
        
<BorderedLabel@Label+Widget>
    border_color: 0, 0, 0, 0.5
    canvas.before:
        Color:
            rgba: root.border_color
        Line:
            width: 2
            rectangle: self.pos[0], self.pos[1], self.size[0], self.size[1]

<PySimbotMap>:
    pos: 0, 0
    # size: 700, 600
    size_hint: None, None
    canvas:
        Color:
            rgba: 1, 0.78, 0.78, 0.5
        Rectangle:
            pos: self.pos
            size: self.size

<Simbot>:
    orientation: 'horizontal'
    size_hint: None, None
    size: 900, 600
    canvas:
        Color:
            rgba: 1, 1, 1, 0.85
        Rectangle:
            pos: self.pos
            size: self.size

    BorderedLabel:
        id: 'lbl_description'
        text: 'Simulation Count: ' + str(root.simulation_count) + '\nTime: '+ str(root.iteration) + '\nEat: ' + str(root.eat_count) + '\nFood Moved: ' + str(root.food_move_count) + '\nScore: ' + root.scoreStr + '\n\n----------------------\n[Shortcuts]\nn: to change the food position'
        text_size: self.size
        padding: (15, 10)
        halign: 'left'
        valign: 'top'
        color: 0.2, 0.2, 0.2, 1